import React from 'react';
import { 
  Printer, 
  Download, 
  FileText, 
  CheckCircle2, 
  ShieldCheck, 
  Building,
  Award
} from 'lucide-react';
import { TenderDocument, BidderSubmission } from '../types/stamas';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  tender: TenderDocument;
  selectedBidder: BidderSubmission;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  tender,
  selectedBidder,
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCSV = () => {
    const headers = [
      'Rule ID',
      'Rule Name',
      'Category',
      'Mandatory',
      'Evaluation Status',
      'Confidence %',
      'Tender Requirement',
      'Bidder Submission',
      'Evidence Quotation',
      'Document Page',
      'Evaluator Notes',
    ];

    const rows = selectedBidder.evaluationResults.map((r) => [
      `"${r.ruleId}"`,
      `"${r.ruleName.replace(/"/g, '""')}"`,
      `"${r.category}"`,
      `"${r.mandatory ? 'YES' : 'NO'}"`,
      `"${r.status}"`,
      `"${r.confidence}%"`,
      `"${r.tenderRequirement.replace(/"/g, '""')}"`,
      `"${r.bidderSubmittedValue.replace(/"/g, '""')}"`,
      `"${r.evidenceQuote.replace(/"/g, '""')}"`,
      `"${r.documentPage || 'N/A'}"`,
      `"${r.notes.replace(/"/g, '""')}"`,
    ]);

    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute(
      'download',
      `STAMAS_Compliance_Matrix_${selectedBidder.bidderName.replace(/\s+/g, '_')}.csv`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadJSON = () => {
    const dataStr =
      'data:text/json;charset=utf-8,' +
      encodeURIComponent(
        JSON.stringify(
          {
            tender: {
              code: tender.code,
              title: tender.title,
              issuer: tender.issuer,
            },
            bidder: selectedBidder,
            exportedAt: new Date().toISOString(),
            engine: 'STAMAS Bid Compliance Engine v2.4',
          },
          null,
          2
        )
      );
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute(
      'download',
      `STAMAS_Audit_${selectedBidder.bidderName.replace(/\s+/g, '_')}.json`
    );
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.removeChild(downloadAnchor);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-3xl w-full p-6 shadow-2xl my-8">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <Award className="w-5 h-5 text-emerald-400" />
            <div>
              <h3 className="text-base font-bold text-white">
                Official Compliance Audit &amp; Evaluation Certificate
              </h3>
              <p className="text-xs text-slate-400">
                Generated by STAMAS Procurement Integrity Engine
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white px-2 py-1 rounded text-sm"
          >
            ✕
          </button>
        </div>

        {/* Printable Certificate Body */}
        <div id="printable-certificate" className="mt-5 p-6 bg-slate-950 rounded-xl border border-slate-800 space-y-4">
          <div className="flex items-start justify-between border-b border-slate-800 pb-4">
            <div>
              <div className="text-[11px] text-emerald-400 uppercase tracking-widest font-bold">
                Tender Verification Audit Record
              </div>
              <h2 className="text-lg font-bold text-white mt-1">{selectedBidder.bidderName}</h2>
              <div className="text-xs text-slate-400 mt-0.5">
                RFP Code: <span className="text-slate-200">{tender.code}</span> · {tender.title}
              </div>
            </div>

            <div className="text-right">
              <div
                className={`text-sm font-extrabold px-3 py-1 rounded border inline-block ${
                  selectedBidder.score.mandatoryPassed
                    ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                    : 'bg-rose-500/10 text-rose-400 border-rose-500/30'
                }`}
              >
                {selectedBidder.score.mandatoryPassed ? 'RESPONSIVE & ELIGIBLE' : 'DISQUALIFIED'}
              </div>
              <div className="text-[11px] text-slate-400 mt-1">
                Score: <strong className="text-white">{selectedBidder.score.overallPercentage}%</strong> · Rank #{selectedBidder.score.rank}
              </div>
            </div>
          </div>

          {/* Quick Metrics */}
          <div className="grid grid-cols-3 gap-3 py-2 text-xs">
            <div className="bg-slate-900 p-2.5 rounded border border-slate-800">
              <span className="text-slate-400 text-[10px] block uppercase font-medium">Commercial Offer</span>
              <span className="text-slate-100 font-bold text-sm">
                ${(selectedBidder.bidAmount / 1_000_000).toFixed(2)}M USD
              </span>
            </div>
            <div className="bg-slate-900 p-2.5 rounded border border-slate-800">
              <span className="text-slate-400 text-[10px] block uppercase font-medium">Mandatory Criteria</span>
              <span className={`font-bold text-sm ${selectedBidder.score.mandatoryPassed ? 'text-emerald-400' : 'text-rose-400'}`}>
                {selectedBidder.score.mandatoryPassed ? 'All Passed' : 'Failed Criteria'}
              </span>
            </div>
            <div className="bg-slate-900 p-2.5 rounded border border-slate-800">
              <span className="text-slate-400 text-[10px] block uppercase font-medium">Verified Results</span>
              <span className="text-slate-100 font-bold text-sm">
                {selectedBidder.score.passCount} Pass · {selectedBidder.score.failCount} Fail · {selectedBidder.score.reviewCount} Rev
              </span>
            </div>
          </div>

          {/* Summary Findings */}
          <div className="text-xs space-y-2 pt-2">
            <div className="font-semibold text-slate-300">Executive Evaluation Summary</div>
            <p className="text-slate-400 leading-relaxed text-[11px]">
              Bid submission document <em>{selectedBidder.documentName}</em> underwent automated optical character recognition, semantic clause correlation, and deterministic rule validation against {tender.rules.length} conditions established by {tender.issuer}.
              {selectedBidder.score.mandatoryPassed
                ? ' The proposal meets all statutory eligibility thresholds and has been advanced to financial evaluation.'
                : ' The proposal failed one or more non-waivable mandatory clauses and has been designated non-responsive pursuant to procurement guidelines.'}
            </p>
          </div>
        </div>

        {/* Export Buttons */}
        <div className="mt-6 flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-slate-800">
          <div className="text-xs text-slate-400">
            Export formats: Printable Audit Sheet · CSV Spreadsheet · JSON
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadJSON}
              className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs rounded-lg border border-slate-700 font-medium transition-colors"
            >
              Export JSON
            </button>
            <button
              onClick={handleDownloadCSV}
              className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs rounded-lg border border-slate-700 font-medium flex items-center gap-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export CSV Matrix</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-lg shadow-sm flex items-center gap-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Official PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
